import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  agentProfiles: defineTable({
    ownerKey: v.string(),
    name: v.string(),
    creature: v.string(),
    vibe: v.string(),
    visibleDescription: v.string(),
    hiddenOperatorNotes: v.string(),
    updatedAt: v.number(),
  }).index("by_owner", ["ownerKey"]),
  userProfiles: defineTable({
    ownerKey: v.string(),
    displayName: v.string(),
    preferredName: v.string(),
    timezone: v.string(),
    locale: v.string(),
    notes: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_owner", ["ownerKey"]),
  googleConnections: defineTable({
    ownerKey: v.string(),
    googleEmail: v.string(),
    accessTokenEnc: v.string(),
    refreshTokenEnc: v.string(),
    expiryAt: v.number(),
    scope: v.array(v.string()),
    calendarIds: v.array(v.string()),
    status: v.union(v.literal("active"), v.literal("stale"), v.literal("revoked")),
    updatedAt: v.number(),
  }).index("by_owner", ["ownerKey"]),
  telegramAccounts: defineTable({
    ownerKey: v.string(),
    telegramUserId: v.string(),
    chatId: v.string(),
    username: v.optional(v.string()),
    allowed: v.boolean(),
    updatedAt: v.number(),
  }).index("by_chat", ["chatId"]),
  conversations: defineTable({
    ownerKey: v.string(),
    channel: v.literal("telegram"),
    externalChatId: v.string(),
    sessionKey: v.string(),
    status: v.union(v.literal("active"), v.literal("waiting_for_confirmation"), v.literal("failed")),
    pendingActionId: v.optional(v.id("pendingActions")),
    lastMessageAt: v.number(),
    updatedAt: v.number(),
  }).index("by_session", ["sessionKey"]),
  messages: defineTable({
    conversationId: v.id("conversations"),
    role: v.union(v.literal("user"), v.literal("assistant"), v.literal("system"), v.literal("tool")),
    text: v.string(),
    structuredJson: v.optional(v.any()),
    correlationId: v.string(),
    createdAt: v.number(),
  }).index("by_conversation", ["conversationId"]),
  contextFragments: defineTable({
    scope: v.union(v.literal("global"), v.literal("owner"), v.literal("feature"), v.literal("conversation")),
    scopeId: v.string(),
    kind: v.union(
      v.literal("IDENTITY"),
      v.literal("SOUL"),
      v.literal("AGENTS"),
      v.literal("TOOLS"),
      v.literal("USER"),
      v.literal("MEMORY"),
      v.literal("POLICY"),
      v.literal("BOOTSTRAP"),
      v.literal("FEATURE")
    ),
    title: v.string(),
    bodyMarkdown: v.string(),
    priority: v.number(),
    active: v.boolean(),
    updatedAt: v.number(),
  }).index("by_scope_kind", ["scope", "scopeId", "kind"]),
  memoryEntries: defineTable({
    ownerKey: v.string(),
    memoryType: v.union(v.literal("fact"), v.literal("preference"), v.literal("workflow"), v.literal("warning"), v.literal("lesson")),
    body: v.string(),
    tags: v.array(v.string()),
    salience: v.number(),
    visibility: v.union(v.literal("main_only"), v.literal("shared_safe")),
    updatedAt: v.number(),
  }).index("by_owner", ["ownerKey"]),
  pendingActions: defineTable({
    ownerKey: v.string(),
    conversationId: v.id("conversations"),
    actionType: v.union(v.literal("create_event"), v.literal("move_event"), v.literal("delete_event")),
    calendarId: v.string(),
    targetEventId: v.optional(v.string()),
    draftPayload: v.any(),
    summaryText: v.string(),
    status: v.union(v.literal("draft"), v.literal("approved"), v.literal("applied"), v.literal("cancelled"), v.literal("expired")),
    expiresAt: v.number(),
    createdAt: v.number(),
  }).index("by_conversation", ["conversationId"]),
  dailyDigests: defineTable({
    ownerKey: v.string(),
    digestDate: v.string(),
    rangeStartIso: v.string(),
    rangeEndIso: v.string(),
    messageText: v.string(),
    sentAt: v.number(),
  }).index("by_owner_date", ["ownerKey", "digestDate"]),
  dailyNotes: defineTable({
    ownerKey: v.string(),
    noteDate: v.string(),
    body: v.string(),
    generatedBy: v.union(v.literal("assistant"), v.literal("operator"), v.literal("system")),
    updatedAt: v.number(),
  }).index("by_owner_date", ["ownerKey", "noteDate"]),
  runLogs: defineTable({
    ownerKey: v.string(),
    correlationId: v.string(),
    phase: v.string(),
    status: v.union(v.literal("started"), v.literal("completed"), v.literal("failed")),
    summary: v.string(),
    details: v.optional(v.any()),
    createdAt: v.number(),
  }).index("by_correlation", ["correlationId"]),
  capabilityInventory: defineTable({
    ownerKey: v.string(),
    capabilityName: v.string(),
    status: v.union(v.literal("verified"), v.literal("unverified"), v.literal("unavailable")),
    verificationMethod: v.string(),
    expectedSignal: v.string(),
    notes: v.optional(v.string()),
    lastVerifiedAt: v.optional(v.number()),
  }).index("by_owner", ["ownerKey"]),
  correctionMemory: defineTable({
    ownerKey: v.string(),
    symptom: v.string(),
    rootCause: v.string(),
    fix: v.string(),
    prevention: v.string(),
    appliesTo: v.string(),
    active: v.boolean(),
    updatedAt: v.number(),
  }).index("by_owner", ["ownerKey"]),
  appConfig: defineTable({
    ownerKey: v.string(),
    timezone: v.string(),
    dailyDigestHour: v.number(),
    dailyDigestMinute: v.number(),
    telegramDigestChatId: v.string(),
    googleCalendarDefaultId: v.string(),
    googleCalendarSelectedIds: v.optional(v.array(v.string())),
    locale: v.string(),
    updatedAt: v.number(),
  }).index("by_owner", ["ownerKey"]),
});
